# Generated by Django 5.2.6 on 2025-10-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cambio_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volumen', models.BigIntegerField(blank=True, null=True)),
                ('rango_dia_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rango_dia_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rango_52w_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rango_52w_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponibilidad', models.BooleanField(default=False)),
                ('provider', models.CharField(default='Yahoo Finance', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'acciones',
                'ordering': ['nombre'],
                'unique_together': {('simbolo', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='acciones.accion')),
            ],
            options={
                'db_table': 'precio_historico',
                'ordering': ['fecha'],
            },
        ),
    ]
