# Generated by Django 5.2.6 on 2025-10-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='accion',
            name='simbolo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='accion',
            name='external_id',
        ),
    ]
