# Generated by Django 5.2.6 on 2025-10-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0002_alter_accion_unique_together_alter_accion_simbolo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioHistorico',
        ),
    ]
