# Generated by Django 5.2.6 on 2025-10-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0003_delete_preciohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='imagen',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
