# Generated by Django 5.2.6 on 2025-10-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0004_accion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='imagen',
        ),
    ]
