# Generated by Django 5.2.7 on 2025-11-02 01:57

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('birth_date', models.DateField(default=None, null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('cellphone', models.CharField(default='', max_length=20)),
                ('dpi', models.CharField(default='', max_length=20, unique=True)),
                ('auth0_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=apps.users.models.get_default_user_state, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='users.profilestate')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_logs', to='users.useraction')),
            ],
        ),
    ]
