# Generated by Django 4.2.7 on 2025-11-04 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbalance_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deposit_transactions',
            },
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userbalance',
            options={},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_expiration',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='alias',
            field=models.CharField(default='Mi método de pago', help_text='Nombre personalizado del método de pago', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('expired', 'Expirado')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='total_deposits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='total_withdrawals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('bank_account', 'Cuenta Bancaria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='routing_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'status'], name='payment_met_user_id_cad3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['created_at'], name='payment_met_created_d444d4_idx'),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paymentmethod'),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['user', 'status'], name='deposit_tra_user_id_0e8711_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['created_at'], name='deposit_tra_created_d5883d_idx'),
        ),
    ]
