# Generated by Django 4.2.7 on 2025-11-04 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_deposittransaction_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_types', models.CharField(help_text='Tipos separados por comas: complete, profile, portfolio, transactions, performance', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En Procesamiento'), ('completed', 'Completado'), ('failed', 'Fallido'), ('sent', 'Enviado')], default='pending', max_length=20)),
                ('report_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_requests',
                'indexes': [models.Index(fields=['user', 'status'], name='report_requ_user_id_a718ab_idx'), models.Index(fields=['created_at'], name='report_requ_created_d3c7c4_idx'), models.Index(fields=['report_code'], name='report_requ_report__e2e00a_idx')],
            },
        ),
    ]
