# Generated by Django 5.2.6 on 2025-10-06 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('compras_ventas', 'Compras y Ventas'), ('ganancias_perdidas', 'Ganancias y Pérdidas'), ('movimientos_cuenta', 'Movimientos de Cuenta'), ('referidos', 'Bonos de Referidos'), ('portafolio', 'Portafolio General')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('formato_salida', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('datos_compras', models.JSONField(blank=True, default=dict)),
                ('datos_ventas', models.JSONField(blank=True, default=dict)),
                ('datos_ganancias_perdidas', models.JSONField(blank=True, default=dict)),
                ('datos_portafolio', models.JSONField(blank=True, default=dict)),
                ('datos_referidos', models.JSONField(blank=True, default=dict)),
                ('datos_movimientos', models.JSONField(blank=True, default=dict)),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('eliminado', models.BooleanField(default=False)),
                ('ip_solicitud', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('jwt_payload', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='reportes.reporte')),
            ],
        ),
    ]
