services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../backend/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ../frontend
    env_file:
      - ../frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
